export const ADD_REMINDER = 'ADD_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';
export const REMOVE_REMINDER = 'REMOVE_REMINDER';
export const REMOVE_ALL_DAY_REMINDERS = 'REMOVE_ALL_DAY_REMINDERS';